// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
@preconcurrency import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(AshCoreFFI)
@preconcurrency import AshCoreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_ash_bindings_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_ash_bindings_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private nonisolated func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private nonisolated func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private nonisolated func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private nonisolated func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Frame for QR code transfer
 */
public protocol FrameProtocol : AnyObject {
    
    /**
     * Encode frame to bytes
     */
    func encode()  -> [UInt8]
    
    /**
     * Get frame index
     */
    func getIndex()  -> UInt16
    
    /**
     * Get payload bytes
     */
    func getPayload()  -> [UInt8]
    
    /**
     * Get total frame count
     */
    func getTotal()  -> UInt16
    
}

/**
 * Frame for QR code transfer
 */
open class Frame:
    FrameProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_ash_bindings_fn_clone_frame(self.pointer, $0) }
    }
    /**
     * Create a new frame
     */
public convenience init(index: UInt16, total: UInt16, payload: [UInt8])throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeAshError.lift) {
    uniffi_ash_bindings_fn_constructor_frame_new(
        FfiConverterUInt16.lower(index),
        FfiConverterUInt16.lower(total),
        FfiConverterSequenceUInt8.lower(payload),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_ash_bindings_fn_free_frame(pointer, $0) }
    }

    
    /**
     * Decode frame from bytes
     */
public static func decode(bytes: [UInt8])throws  -> Frame {
    return try  FfiConverterTypeFrame.lift(try rustCallWithError(FfiConverterTypeAshError.lift) {
    uniffi_ash_bindings_fn_constructor_frame_decode(
        FfiConverterSequenceUInt8.lower(bytes),$0
    )
})
}
    

    
    /**
     * Encode frame to bytes
     */
open func encode() -> [UInt8] {
    return try!  FfiConverterSequenceUInt8.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_frame_encode(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get frame index
     */
open func getIndex() -> UInt16 {
    return try!  FfiConverterUInt16.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_frame_get_index(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get payload bytes
     */
open func getPayload() -> [UInt8] {
    return try!  FfiConverterSequenceUInt8.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_frame_get_payload(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get total frame count
     */
open func getTotal() -> UInt16 {
    return try!  FfiConverterUInt16.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_frame_get_total(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFrame: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Frame

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Frame {
        return Frame(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Frame) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Frame {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Frame, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFrame_lift(_ pointer: UnsafeMutableRawPointer) throws -> Frame {
    return try FfiConverterTypeFrame.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFrame_lower(_ value: Frame) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFrame.lower(value)
}




/**
 * One-Time Pad with single-use consumption semantics
 */
public protocol PadProtocol : AnyObject {
    
    /**
     * Get raw bytes for ceremony transfer
     */
    func asBytes()  -> [UInt8]
    
    /**
     * Consume next n bytes from pad
     */
    func consume(n: UInt32) throws  -> [UInt8]
    
    /**
     * Get consumed bytes count
     */
    func consumed()  -> UInt64
    
    /**
     * Check if pad is exhausted
     */
    func isExhausted()  -> Bool
    
    /**
     * Get remaining bytes count
     */
    func remaining()  -> UInt64
    
    /**
     * Get total pad size
     */
    func totalSize()  -> UInt64
    
}

/**
 * One-Time Pad with single-use consumption semantics
 */
open class Pad:
    PadProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_ash_bindings_fn_clone_pad(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_ash_bindings_fn_free_pad(pointer, $0) }
    }

    
    /**
     * Create pad from raw bytes (for reconstruction)
     */
public static func fromBytes(bytes: [UInt8]) -> Pad {
    return try!  FfiConverterTypePad.lift(try! rustCall() {
    uniffi_ash_bindings_fn_constructor_pad_from_bytes(
        FfiConverterSequenceUInt8.lower(bytes),$0
    )
})
}
    
    /**
     * Create pad from entropy bytes
     */
public static func fromEntropy(entropy: [UInt8], size: PadSize)throws  -> Pad {
    return try  FfiConverterTypePad.lift(try rustCallWithError(FfiConverterTypeAshError.lift) {
    uniffi_ash_bindings_fn_constructor_pad_from_entropy(
        FfiConverterSequenceUInt8.lower(entropy),
        FfiConverterTypePadSize.lower(size),$0
    )
})
}
    

    
    /**
     * Get raw bytes for ceremony transfer
     */
open func asBytes() -> [UInt8] {
    return try!  FfiConverterSequenceUInt8.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_pad_as_bytes(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Consume next n bytes from pad
     */
open func consume(n: UInt32)throws  -> [UInt8] {
    return try  FfiConverterSequenceUInt8.lift(try rustCallWithError(FfiConverterTypeAshError.lift) {
    uniffi_ash_bindings_fn_method_pad_consume(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(n),$0
    )
})
}
    
    /**
     * Get consumed bytes count
     */
open func consumed() -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_pad_consumed(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Check if pad is exhausted
     */
open func isExhausted() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_pad_is_exhausted(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get remaining bytes count
     */
open func remaining() -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_pad_remaining(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get total pad size
     */
open func totalSize() -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_pad_total_size(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePad: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Pad

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Pad {
        return Pad(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Pad) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Pad {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Pad, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePad_lift(_ pointer: UnsafeMutableRawPointer) throws -> Pad {
    return try FfiConverterTypePad.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePad_lower(_ value: Pad) -> UnsafeMutableRawPointer {
    return FfiConverterTypePad.lower(value)
}


/**
 * Error types for ASH operations
 */
public enum AshError {

    
    
    /**
     * Not enough bytes remaining in pad
     */
    case InsufficientPadBytes(message: String)
    
    /**
     * Entropy size doesn't match expected pad size
     */
    case InvalidEntropySize(message: String)
    
    /**
     * Pad is fully consumed
     */
    case PadExhausted(message: String)
    
    /**
     * Key and data lengths don't match
     */
    case LengthMismatch(message: String)
    
    /**
     * Frame data is too short
     */
    case FrameTooShort(message: String)
    
    /**
     * CRC checksum failed
     */
    case CrcMismatch(message: String)
    
    /**
     * Frame index exceeds total count
     */
    case FrameIndexOutOfBounds(message: String)
    
    /**
     * Frames have inconsistent totals
     */
    case FrameCountMismatch(message: String)
    
    /**
     * Some frames are missing
     */
    case MissingFrames(message: String)
    
    /**
     * Duplicate frame index
     */
    case DuplicateFrame(message: String)
    
    /**
     * Payload cannot be empty
     */
    case EmptyPayload(message: String)
    
    /**
     * Payload exceeds maximum size
     */
    case PayloadTooLarge(message: String)
    
    /**
     * No frames provided
     */
    case NoFrames(message: String)
    
    /**
     * Total frame count is zero
     */
    case ZeroTotalFrames(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAshError: FfiConverterRustBuffer {
    typealias SwiftType = AshError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AshError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InsufficientPadBytes(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .InvalidEntropySize(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .PadExhausted(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .LengthMismatch(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .FrameTooShort(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .CrcMismatch(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .FrameIndexOutOfBounds(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .FrameCountMismatch(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 9: return .MissingFrames(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 10: return .DuplicateFrame(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 11: return .EmptyPayload(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 12: return .PayloadTooLarge(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 13: return .NoFrames(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 14: return .ZeroTotalFrames(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AshError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .InsufficientPadBytes(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .InvalidEntropySize(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .PadExhausted(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .LengthMismatch(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .FrameTooShort(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .CrcMismatch(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .FrameIndexOutOfBounds(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))
        case .FrameCountMismatch(_ /* message is ignored*/):
            writeInt(&buf, Int32(8))
        case .MissingFrames(_ /* message is ignored*/):
            writeInt(&buf, Int32(9))
        case .DuplicateFrame(_ /* message is ignored*/):
            writeInt(&buf, Int32(10))
        case .EmptyPayload(_ /* message is ignored*/):
            writeInt(&buf, Int32(11))
        case .PayloadTooLarge(_ /* message is ignored*/):
            writeInt(&buf, Int32(12))
        case .NoFrames(_ /* message is ignored*/):
            writeInt(&buf, Int32(13))
        case .ZeroTotalFrames(_ /* message is ignored*/):
            writeInt(&buf, Int32(14))

        
        }
    }
}


extension AshError: Equatable, Hashable {}

extension AshError: Foundation.LocalizedError {
    public nonisolated var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Pad size options
 */

public enum PadSize {
    
    /**
     * 64 KB - ~50 messages, ~1-2 min transfer
     */
    case small
    /**
     * 256 KB - ~200 messages, ~4-5 min transfer
     */
    case medium
    /**
     * 1 MB - ~800 messages, ~15-20 min transfer
     */
    case large
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePadSize: FfiConverterRustBuffer {
    typealias SwiftType = PadSize

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PadSize {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .small
        
        case 2: return .medium
        
        case 3: return .large
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PadSize, into buf: inout [UInt8]) {
        switch value {
        
        
        case .small:
            writeInt(&buf, Int32(1))
        
        
        case .medium:
            writeInt(&buf, Int32(2))
        
        
        case .large:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePadSize_lift(_ buf: RustBuffer) throws -> PadSize {
    return try FfiConverterTypePadSize.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePadSize_lower(_ value: PadSize) -> RustBuffer {
    return FfiConverterTypePadSize.lower(value)
}



extension PadSize: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [UInt8]

    public static func write(_ value: [UInt8], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt8.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt8] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt8]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt8.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFrame: FfiConverterRustBuffer {
    typealias SwiftType = [Frame]

    public static func write(_ value: [Frame], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFrame.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Frame] {
        let len: Int32 = try readInt(&buf)
        var seq = [Frame]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFrame.read(from: &buf))
        }
        return seq
    }
}
/**
 * Create frames from pad bytes for QR transfer
 */
public nonisolated func createFrames(padBytes: [UInt8], maxPayload: UInt32)throws  -> [Frame] {
    return try  FfiConverterSequenceTypeFrame.lift(try rustCallWithError(FfiConverterTypeAshError.lift) {
    uniffi_ash_bindings_fn_func_create_frames(
        FfiConverterSequenceUInt8.lower(padBytes),
        FfiConverterUInt32.lower(maxPayload),$0
    )
})
}
/**
 * Decrypt ciphertext using OTP (XOR with key)
 */
public nonisolated func decrypt(key: [UInt8], ciphertext: [UInt8])throws  -> [UInt8] {
    return try  FfiConverterSequenceUInt8.lift(try rustCallWithError(FfiConverterTypeAshError.lift) {
    uniffi_ash_bindings_fn_func_decrypt(
        FfiConverterSequenceUInt8.lower(key),
        FfiConverterSequenceUInt8.lower(ciphertext),$0
    )
})
}
/**
 * Encrypt plaintext using OTP (XOR with key)
 */
public nonisolated func encrypt(key: [UInt8], plaintext: [UInt8])throws  -> [UInt8] {
    return try  FfiConverterSequenceUInt8.lift(try rustCallWithError(FfiConverterTypeAshError.lift) {
    uniffi_ash_bindings_fn_func_encrypt(
        FfiConverterSequenceUInt8.lower(key),
        FfiConverterSequenceUInt8.lower(plaintext),$0
    )
})
}
/**
 * Generate 6-word mnemonic checksum from pad bytes
 */
public nonisolated func generateMnemonic(padBytes: [UInt8]) -> [String] {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_ash_bindings_fn_func_generate_mnemonic(
        FfiConverterSequenceUInt8.lower(padBytes),$0
    )
})
}
/**
 * Generate mnemonic with custom word count
 */
public nonisolated func generateMnemonicWithCount(padBytes: [UInt8], wordCount: UInt32) -> [String] {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_ash_bindings_fn_func_generate_mnemonic_with_count(
        FfiConverterSequenceUInt8.lower(padBytes),
        FfiConverterUInt32.lower(wordCount),$0
    )
})
}
/**
 * Reconstruct pad from received frames
 */
public nonisolated func reconstructPad(frames: [Frame])throws  -> [UInt8] {
    return try  FfiConverterSequenceUInt8.lift(try rustCallWithError(FfiConverterTypeAshError.lift) {
    uniffi_ash_bindings_fn_func_reconstruct_pad(
        FfiConverterSequenceTypeFrame.lower(frames),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
nonisolated(unsafe) private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_ash_bindings_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_ash_bindings_checksum_func_create_frames() != 30542) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_func_decrypt() != 24750) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_func_encrypt() != 28557) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_func_generate_mnemonic() != 8039) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_func_generate_mnemonic_with_count() != 38577) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_func_reconstruct_pad() != 57265) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_frame_encode() != 41007) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_frame_get_index() != 3514) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_frame_get_payload() != 26916) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_frame_get_total() != 33409) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_pad_as_bytes() != 57196) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_pad_consume() != 25970) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_pad_consumed() != 16684) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_pad_is_exhausted() != 34846) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_pad_remaining() != 32900) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_pad_total_size() != 20873) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_constructor_frame_decode() != 40558) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_constructor_frame_new() != 6507) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_constructor_pad_from_bytes() != 21075) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_constructor_pad_from_entropy() != 28891) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private nonisolated func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all