// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(AshCoreFFI)
import AshCoreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_ash_bindings_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_ash_bindings_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public nonisolated var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private nonisolated func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private nonisolated func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private nonisolated func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private nonisolated func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Fountain frame generator for QR display.
 *
 * Generates unlimited encoded blocks from ceremony data. The display
 * cycles through blocks until the receiver signals completion.
 *
 * # Block Types
 *
 * - Blocks 0..K: Source blocks (direct data, no encoding overhead)
 * - Blocks K+: XOR blocks (combinations of two source blocks)
 */
public protocol FountainFrameGeneratorProtocol : AnyObject {
    
    /**
     * Block size in bytes.
     */
    func blockSize()  -> UInt32
    
    /**
     * Generate a specific block by index.
     *
     * Useful for regenerating specific blocks or random access.
     * Same index always produces same block (deterministic).
     */
    func generateFrame(index: UInt32)  -> [UInt8]
    
    /**
     * Generate the next QR frame bytes.
     *
     * Can be called infinitely - generates new blocks each time.
     * Blocks cycle through source blocks first, then XOR blocks.
     */
    func nextFrame()  -> [UInt8]
    
    /**
     * Number of source blocks (minimum needed for decoding).
     */
    func sourceCount()  -> UInt32
    
    /**
     * Total data size being transferred (metadata + pad).
     */
    func totalSize()  -> UInt32
    
}

/**
 * Fountain frame generator for QR display.
 *
 * Generates unlimited encoded blocks from ceremony data. The display
 * cycles through blocks until the receiver signals completion.
 *
 * # Block Types
 *
 * - Blocks 0..K: Source blocks (direct data, no encoding overhead)
 * - Blocks K+: XOR blocks (combinations of two source blocks)
 */
open class FountainFrameGenerator:
    FountainFrameGeneratorProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_ash_bindings_fn_clone_fountainframegenerator(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_ash_bindings_fn_free_fountainframegenerator(pointer, $0) }
    }

    

    
    /**
     * Block size in bytes.
     */
open func blockSize() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_fountainframegenerator_block_size(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Generate a specific block by index.
     *
     * Useful for regenerating specific blocks or random access.
     * Same index always produces same block (deterministic).
     */
open func generateFrame(index: UInt32) -> [UInt8] {
    return try!  FfiConverterSequenceUInt8.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_fountainframegenerator_generate_frame(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(index),$0
    )
})
}
    
    /**
     * Generate the next QR frame bytes.
     *
     * Can be called infinitely - generates new blocks each time.
     * Blocks cycle through source blocks first, then XOR blocks.
     */
open func nextFrame() -> [UInt8] {
    return try!  FfiConverterSequenceUInt8.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_fountainframegenerator_next_frame(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Number of source blocks (minimum needed for decoding).
     */
open func sourceCount() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_fountainframegenerator_source_count(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Total data size being transferred (metadata + pad).
     */
open func totalSize() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_fountainframegenerator_total_size(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFountainFrameGenerator: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FountainFrameGenerator

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FountainFrameGenerator {
        return FountainFrameGenerator(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FountainFrameGenerator) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FountainFrameGenerator {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FountainFrameGenerator, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFountainFrameGenerator_lift(_ pointer: UnsafeMutableRawPointer) throws -> FountainFrameGenerator {
    return try FfiConverterTypeFountainFrameGenerator.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFountainFrameGenerator_lower(_ value: FountainFrameGenerator) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFountainFrameGenerator.lower(value)
}




/**
 * Fountain frame receiver for QR scanning.
 *
 * Collects scanned blocks and tracks decoding progress.
 * Can decode from ANY sufficient subset of blocks.
 */
public protocol FountainFrameReceiverProtocol : AnyObject {
    
    /**
     * Add a scanned QR frame.
     *
     * Returns true if decoding is now complete, false if more blocks needed.
     * Duplicate blocks are safely ignored.
     */
    func addFrame(frameBytes: [UInt8]) throws  -> Bool
    
    /**
     * Number of blocks received (including duplicates).
     */
    func blocksReceived()  -> UInt32
    
    /**
     * Get the decoded ceremony result.
     * Returns null if decoding is not complete.
     */
    func getResult()  -> FountainCeremonyResult?
    
    /**
     * Check if decoding is complete.
     */
    func isComplete()  -> Bool
    
    /**
     * Get decoding progress (0.0 to 1.0).
     */
    func progress()  -> Double
    
    /**
     * Number of source blocks needed for complete decoding.
     * Returns 0 before the first block is received.
     */
    func sourceCount()  -> UInt32
    
}

/**
 * Fountain frame receiver for QR scanning.
 *
 * Collects scanned blocks and tracks decoding progress.
 * Can decode from ANY sufficient subset of blocks.
 */
open class FountainFrameReceiver:
    FountainFrameReceiverProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_ash_bindings_fn_clone_fountainframereceiver(self.pointer, $0) }
    }
    /**
     * Create a new receiver.
     *
     * If passphrase was used for encryption, same passphrase must be provided.
     */
public convenience init(passphrase: String?) {
    let pointer =
        try! rustCall() {
    uniffi_ash_bindings_fn_constructor_fountainframereceiver_new(
        FfiConverterOptionString.lower(passphrase),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_ash_bindings_fn_free_fountainframereceiver(pointer, $0) }
    }

    

    
    /**
     * Add a scanned QR frame.
     *
     * Returns true if decoding is now complete, false if more blocks needed.
     * Duplicate blocks are safely ignored.
     */
open func addFrame(frameBytes: [UInt8])throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeAshError.lift) {
    uniffi_ash_bindings_fn_method_fountainframereceiver_add_frame(self.uniffiClonePointer(),
        FfiConverterSequenceUInt8.lower(frameBytes),$0
    )
})
}
    
    /**
     * Number of blocks received (including duplicates).
     */
open func blocksReceived() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_fountainframereceiver_blocks_received(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get the decoded ceremony result.
     * Returns null if decoding is not complete.
     */
open func getResult() -> FountainCeremonyResult? {
    return try!  FfiConverterOptionTypeFountainCeremonyResult.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_fountainframereceiver_get_result(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Check if decoding is complete.
     */
open func isComplete() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_fountainframereceiver_is_complete(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get decoding progress (0.0 to 1.0).
     */
open func progress() -> Double {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_fountainframereceiver_progress(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Number of source blocks needed for complete decoding.
     * Returns 0 before the first block is received.
     */
open func sourceCount() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_fountainframereceiver_source_count(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFountainFrameReceiver: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FountainFrameReceiver

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FountainFrameReceiver {
        return FountainFrameReceiver(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FountainFrameReceiver) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FountainFrameReceiver {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FountainFrameReceiver, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFountainFrameReceiver_lift(_ pointer: UnsafeMutableRawPointer) throws -> FountainFrameReceiver {
    return try FfiConverterTypeFountainFrameReceiver.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFountainFrameReceiver_lower(_ value: FountainFrameReceiver) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFountainFrameReceiver.lower(value)
}




/**
 * One-Time Pad with bidirectional consumption semantics
 *
 * The pad uses bidirectional consumption:
 * - Initiator consumes from the start of the pad
 * - Responder consumes from the end of the pad
 *
 * This allows both parties to send messages without coordination.
 */
public protocol PadProtocol : AnyObject {
    
    /**
     * Get raw bytes for ceremony transfer
     */
    func asBytes()  -> [UInt8]
    
    /**
     * Get the number of bytes available for sending (dynamic allocation)
     */
    func availableForSending(role: Role)  -> UInt64
    
    /**
     * Check if we can send a message of the given length (dynamic allocation)
     */
    func canSend(length: UInt32, role: Role)  -> Bool
    
    /**
     * Consume next n bytes from pad based on role
     * - Initiator consumes from the start (moving forward)
     * - Responder consumes from the end (moving backward)
     */
    func consume(n: UInt32, role: Role) throws  -> [UInt8]
    
    /**
     * Get total consumed bytes count (both directions)
     */
    func consumed()  -> UInt64
    
    /**
     * Get bytes consumed from end (by Responder)
     */
    func consumedBack()  -> UInt64
    
    /**
     * Get bytes consumed from start (by Initiator)
     */
    func consumedFront()  -> UInt64
    
    /**
     * Check if pad is exhausted
     */
    func isExhausted()  -> Bool
    
    /**
     * Get the offset for the next message we send
     */
    func nextSendOffset(role: Role)  -> UInt64
    
    /**
     * Get remaining bytes count (available for either role)
     */
    func remaining()  -> UInt64
    
    /**
     * Get total pad size
     */
    func totalSize()  -> UInt64
    
    /**
     * Update peer's consumption based on a received message
     */
    func updatePeerConsumption(peerRole: Role, newConsumed: UInt64) 
    
}

/**
 * One-Time Pad with bidirectional consumption semantics
 *
 * The pad uses bidirectional consumption:
 * - Initiator consumes from the start of the pad
 * - Responder consumes from the end of the pad
 *
 * This allows both parties to send messages without coordination.
 */
open class Pad:
    PadProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_ash_bindings_fn_clone_pad(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_ash_bindings_fn_free_pad(pointer, $0) }
    }

    
    /**
     * Create pad from raw bytes (for reconstruction)
     */
public static func fromBytes(bytes: [UInt8]) -> Pad {
    return try!  FfiConverterTypePad.lift(try! rustCall() {
    uniffi_ash_bindings_fn_constructor_pad_from_bytes(
        FfiConverterSequenceUInt8.lower(bytes),$0
    )
})
}
    
    /**
     * Create pad from raw bytes with pre-existing consumption state
     * Used when restoring a pad from persistent storage.
     */
public static func fromBytesWithState(bytes: [UInt8], consumedFront: UInt64, consumedBack: UInt64) -> Pad {
    return try!  FfiConverterTypePad.lift(try! rustCall() {
    uniffi_ash_bindings_fn_constructor_pad_from_bytes_with_state(
        FfiConverterSequenceUInt8.lower(bytes),
        FfiConverterUInt64.lower(consumedFront),
        FfiConverterUInt64.lower(consumedBack),$0
    )
})
}
    
    /**
     * Create pad from entropy bytes
     */
public static func fromEntropy(entropy: [UInt8], size: PadSize)throws  -> Pad {
    return try  FfiConverterTypePad.lift(try rustCallWithError(FfiConverterTypeAshError.lift) {
    uniffi_ash_bindings_fn_constructor_pad_from_entropy(
        FfiConverterSequenceUInt8.lower(entropy),
        FfiConverterTypePadSize.lower(size),$0
    )
})
}
    

    
    /**
     * Get raw bytes for ceremony transfer
     */
open func asBytes() -> [UInt8] {
    return try!  FfiConverterSequenceUInt8.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_pad_as_bytes(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get the number of bytes available for sending (dynamic allocation)
     */
open func availableForSending(role: Role) -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_pad_available_for_sending(self.uniffiClonePointer(),
        FfiConverterTypeRole.lower(role),$0
    )
})
}
    
    /**
     * Check if we can send a message of the given length (dynamic allocation)
     */
open func canSend(length: UInt32, role: Role) -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_pad_can_send(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(length),
        FfiConverterTypeRole.lower(role),$0
    )
})
}
    
    /**
     * Consume next n bytes from pad based on role
     * - Initiator consumes from the start (moving forward)
     * - Responder consumes from the end (moving backward)
     */
open func consume(n: UInt32, role: Role)throws  -> [UInt8] {
    return try  FfiConverterSequenceUInt8.lift(try rustCallWithError(FfiConverterTypeAshError.lift) {
    uniffi_ash_bindings_fn_method_pad_consume(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(n),
        FfiConverterTypeRole.lower(role),$0
    )
})
}
    
    /**
     * Get total consumed bytes count (both directions)
     */
open func consumed() -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_pad_consumed(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get bytes consumed from end (by Responder)
     */
open func consumedBack() -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_pad_consumed_back(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get bytes consumed from start (by Initiator)
     */
open func consumedFront() -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_pad_consumed_front(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Check if pad is exhausted
     */
open func isExhausted() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_pad_is_exhausted(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get the offset for the next message we send
     */
open func nextSendOffset(role: Role) -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_pad_next_send_offset(self.uniffiClonePointer(),
        FfiConverterTypeRole.lower(role),$0
    )
})
}
    
    /**
     * Get remaining bytes count (available for either role)
     */
open func remaining() -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_pad_remaining(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get total pad size
     */
open func totalSize() -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_ash_bindings_fn_method_pad_total_size(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Update peer's consumption based on a received message
     */
open func updatePeerConsumption(peerRole: Role, newConsumed: UInt64) {try! rustCall() {
    uniffi_ash_bindings_fn_method_pad_update_peer_consumption(self.uniffiClonePointer(),
        FfiConverterTypeRole.lower(peerRole),
        FfiConverterUInt64.lower(newConsumed),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePad: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Pad

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Pad {
        return Pad(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Pad) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Pad {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Pad, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePad_lift(_ pointer: UnsafeMutableRawPointer) throws -> Pad {
    return try FfiConverterTypePad.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePad_lower(_ value: Pad) -> UnsafeMutableRawPointer {
    return FfiConverterTypePad.lower(value)
}


/**
 * Authorization tokens derived from pad during ceremony
 */
public struct AuthTokens {
    /**
     * Conversation ID (hex-encoded, 64 chars)
     */
    public let conversationId: String
    /**
     * Auth token for API operations (hex-encoded, 64 chars)
     */
    public let authToken: String
    /**
     * Burn token for burn operations (hex-encoded, 64 chars)
     */
    public let burnToken: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Conversation ID (hex-encoded, 64 chars)
         */conversationId: String, 
        /**
         * Auth token for API operations (hex-encoded, 64 chars)
         */authToken: String, 
        /**
         * Burn token for burn operations (hex-encoded, 64 chars)
         */burnToken: String) {
        self.conversationId = conversationId
        self.authToken = authToken
        self.burnToken = burnToken
    }
}



extension AuthTokens: Equatable, Hashable {
    public static func ==(lhs: AuthTokens, rhs: AuthTokens) -> Bool {
        if lhs.conversationId != rhs.conversationId {
            return false
        }
        if lhs.authToken != rhs.authToken {
            return false
        }
        if lhs.burnToken != rhs.burnToken {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(conversationId)
        hasher.combine(authToken)
        hasher.combine(burnToken)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAuthTokens: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AuthTokens {
        return
            try AuthTokens(
                conversationId: FfiConverterString.read(from: &buf), 
                authToken: FfiConverterString.read(from: &buf), 
                burnToken: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: AuthTokens, into buf: inout [UInt8]) {
        FfiConverterString.write(value.conversationId, into: &buf)
        FfiConverterString.write(value.authToken, into: &buf)
        FfiConverterString.write(value.burnToken, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAuthTokens_lift(_ buf: RustBuffer) throws -> AuthTokens {
    return try FfiConverterTypeAuthTokens.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAuthTokens_lower(_ value: AuthTokens) -> RustBuffer {
    return FfiConverterTypeAuthTokens.lower(value)
}


/**
 * Ceremony metadata transferred via QR frame 0
 * Contains settings agreed upon during ceremony
 */
public struct CeremonyMetadata {
    /**
     * Protocol version (always 1)
     */
    public let version: UInt8
    /**
     * Message TTL in seconds (default 300 = 5 minutes)
     */
    public let ttlSeconds: UInt64
    /**
     * Disappearing messages timeout in seconds (0 = off)
     */
    public let disappearingMessagesSeconds: UInt32
    /**
     * Relay server URL
     */
    public let relayUrl: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Protocol version (always 1)
         */version: UInt8, 
        /**
         * Message TTL in seconds (default 300 = 5 minutes)
         */ttlSeconds: UInt64, 
        /**
         * Disappearing messages timeout in seconds (0 = off)
         */disappearingMessagesSeconds: UInt32, 
        /**
         * Relay server URL
         */relayUrl: String) {
        self.version = version
        self.ttlSeconds = ttlSeconds
        self.disappearingMessagesSeconds = disappearingMessagesSeconds
        self.relayUrl = relayUrl
    }
}



extension CeremonyMetadata: Equatable, Hashable {
    public static func ==(lhs: CeremonyMetadata, rhs: CeremonyMetadata) -> Bool {
        if lhs.version != rhs.version {
            return false
        }
        if lhs.ttlSeconds != rhs.ttlSeconds {
            return false
        }
        if lhs.disappearingMessagesSeconds != rhs.disappearingMessagesSeconds {
            return false
        }
        if lhs.relayUrl != rhs.relayUrl {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(version)
        hasher.combine(ttlSeconds)
        hasher.combine(disappearingMessagesSeconds)
        hasher.combine(relayUrl)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCeremonyMetadata: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CeremonyMetadata {
        return
            try CeremonyMetadata(
                version: FfiConverterUInt8.read(from: &buf), 
                ttlSeconds: FfiConverterUInt64.read(from: &buf), 
                disappearingMessagesSeconds: FfiConverterUInt32.read(from: &buf), 
                relayUrl: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: CeremonyMetadata, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.version, into: &buf)
        FfiConverterUInt64.write(value.ttlSeconds, into: &buf)
        FfiConverterUInt32.write(value.disappearingMessagesSeconds, into: &buf)
        FfiConverterString.write(value.relayUrl, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCeremonyMetadata_lift(_ buf: RustBuffer) throws -> CeremonyMetadata {
    return try FfiConverterTypeCeremonyMetadata.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCeremonyMetadata_lower(_ value: CeremonyMetadata) -> RustBuffer {
    return FfiConverterTypeCeremonyMetadata.lower(value)
}


/**
 * Result of fountain ceremony decoding
 */
public struct FountainCeremonyResult {
    /**
     * Ceremony metadata (settings)
     */
    public let metadata: CeremonyMetadata
    /**
     * Reconstructed pad bytes
     */
    public let pad: [UInt8]
    /**
     * Number of blocks used for decoding
     */
    public let blocksUsed: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Ceremony metadata (settings)
         */metadata: CeremonyMetadata, 
        /**
         * Reconstructed pad bytes
         */pad: [UInt8], 
        /**
         * Number of blocks used for decoding
         */blocksUsed: UInt32) {
        self.metadata = metadata
        self.pad = pad
        self.blocksUsed = blocksUsed
    }
}



extension FountainCeremonyResult: Equatable, Hashable {
    public static func ==(lhs: FountainCeremonyResult, rhs: FountainCeremonyResult) -> Bool {
        if lhs.metadata != rhs.metadata {
            return false
        }
        if lhs.pad != rhs.pad {
            return false
        }
        if lhs.blocksUsed != rhs.blocksUsed {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(metadata)
        hasher.combine(pad)
        hasher.combine(blocksUsed)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFountainCeremonyResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FountainCeremonyResult {
        return
            try FountainCeremonyResult(
                metadata: FfiConverterTypeCeremonyMetadata.read(from: &buf), 
                pad: FfiConverterSequenceUInt8.read(from: &buf), 
                blocksUsed: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FountainCeremonyResult, into buf: inout [UInt8]) {
        FfiConverterTypeCeremonyMetadata.write(value.metadata, into: &buf)
        FfiConverterSequenceUInt8.write(value.pad, into: &buf)
        FfiConverterUInt32.write(value.blocksUsed, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFountainCeremonyResult_lift(_ buf: RustBuffer) throws -> FountainCeremonyResult {
    return try FfiConverterTypeFountainCeremonyResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFountainCeremonyResult_lower(_ value: FountainCeremonyResult) -> RustBuffer {
    return FfiConverterTypeFountainCeremonyResult.lower(value)
}


/**
 * Error types for ASH operations
 */
public enum AshError {

    
    
    /**
     * Not enough bytes remaining in pad
     */
    case InsufficientPadBytes(message: String)
    
    /**
     * Entropy size doesn't match expected pad size
     */
    case InvalidEntropySize(message: String)
    
    /**
     * Key and data lengths don't match
     */
    case LengthMismatch(message: String)
    
    /**
     * CRC checksum failed
     */
    case CrcMismatch(message: String)
    
    /**
     * Payload cannot be empty
     */
    case EmptyPayload(message: String)
    
    /**
     * Fountain block is too short
     */
    case FountainBlockTooShort(message: String)
    
    /**
     * Metadata frame is too short
     */
    case MetadataTooShort(message: String)
    
    /**
     * Unsupported metadata version
     */
    case UnsupportedMetadataVersion(message: String)
    
    /**
     * Metadata URL is too long
     */
    case MetadataUrlTooLong(message: String)
    
    /**
     * Invalid UTF-8 in metadata URL
     */
    case InvalidMetadataUrl(message: String)
    
    /**
     * Pad is too small to derive authorization tokens
     */
    case PadTooSmallForTokens(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAshError: FfiConverterRustBuffer {
    typealias SwiftType = AshError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AshError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InsufficientPadBytes(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .InvalidEntropySize(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .LengthMismatch(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .CrcMismatch(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .EmptyPayload(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .FountainBlockTooShort(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .MetadataTooShort(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .UnsupportedMetadataVersion(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 9: return .MetadataUrlTooLong(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 10: return .InvalidMetadataUrl(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 11: return .PadTooSmallForTokens(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AshError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .InsufficientPadBytes(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .InvalidEntropySize(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .LengthMismatch(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .CrcMismatch(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .EmptyPayload(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .FountainBlockTooShort(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .MetadataTooShort(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))
        case .UnsupportedMetadataVersion(_ /* message is ignored*/):
            writeInt(&buf, Int32(8))
        case .MetadataUrlTooLong(_ /* message is ignored*/):
            writeInt(&buf, Int32(9))
        case .InvalidMetadataUrl(_ /* message is ignored*/):
            writeInt(&buf, Int32(10))
        case .PadTooSmallForTokens(_ /* message is ignored*/):
            writeInt(&buf, Int32(11))

        
        }
    }
}


extension AshError: Equatable, Hashable {}

extension AshError: Foundation.LocalizedError {
    public nonisolated var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Pad size options
 */

public enum PadSize {
    
    /**
     * 32 KB - ~25 messages, ~25 QR frames
     */
    case tiny
    /**
     * 64 KB - ~50 messages, ~45 QR frames
     */
    case small
    /**
     * 256 KB - ~200 messages, ~177 QR frames
     */
    case medium
    /**
     * 512 KB - ~400 messages, ~353 QR frames
     */
    case large
    /**
     * 1 MB - ~800 messages, ~705 QR frames
     */
    case huge
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePadSize: FfiConverterRustBuffer {
    typealias SwiftType = PadSize

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PadSize {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .tiny
        
        case 2: return .small
        
        case 3: return .medium
        
        case 4: return .large
        
        case 5: return .huge
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PadSize, into buf: inout [UInt8]) {
        switch value {
        
        
        case .tiny:
            writeInt(&buf, Int32(1))
        
        
        case .small:
            writeInt(&buf, Int32(2))
        
        
        case .medium:
            writeInt(&buf, Int32(3))
        
        
        case .large:
            writeInt(&buf, Int32(4))
        
        
        case .huge:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePadSize_lift(_ buf: RustBuffer) throws -> PadSize {
    return try FfiConverterTypePadSize.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePadSize_lower(_ value: PadSize) -> RustBuffer {
    return FfiConverterTypePadSize.lower(value)
}



extension PadSize: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Role in the conversation, determining pad consumption direction.
 *
 * The role is established during the ceremony:
 * - Initiator: The person who creates the ceremony (displays QR codes)
 * - Responder: The person who scans the ceremony QR codes
 */

public enum Role {
    
    /**
     * Initiator consumes from the start of the pad
     */
    case initiator
    /**
     * Responder consumes from the end of the pad
     */
    case responder
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRole: FfiConverterRustBuffer {
    typealias SwiftType = Role

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Role {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .initiator
        
        case 2: return .responder
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Role, into buf: inout [UInt8]) {
        switch value {
        
        
        case .initiator:
            writeInt(&buf, Int32(1))
        
        
        case .responder:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRole_lift(_ buf: RustBuffer) throws -> Role {
    return try FfiConverterTypeRole.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRole_lower(_ value: Role) -> RustBuffer {
    return FfiConverterTypeRole.lower(value)
}



extension Role: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFountainCeremonyResult: FfiConverterRustBuffer {
    typealias SwiftType = FountainCeremonyResult?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFountainCeremonyResult.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFountainCeremonyResult.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [UInt8]

    public static func write(_ value: [UInt8], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt8.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt8] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt8]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt8.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}
/**
 * Create a fountain frame generator for ceremony QR display.
 *
 * This is the main entry point for initiators. The generator produces
 * unlimited encoded blocks that can be displayed as QR codes.
 */
public func createFountainGenerator(metadata: CeremonyMetadata, padBytes: [UInt8], blockSize: UInt32, passphrase: String?)throws  -> FountainFrameGenerator {
    return try  FfiConverterTypeFountainFrameGenerator.lift(try rustCallWithError(FfiConverterTypeAshError.lift) {
    uniffi_ash_bindings_fn_func_create_fountain_generator(
        FfiConverterTypeCeremonyMetadata.lower(metadata),
        FfiConverterSequenceUInt8.lower(padBytes),
        FfiConverterUInt32.lower(blockSize),
        FfiConverterOptionString.lower(passphrase),$0
    )
})
}
/**
 * Decrypt ciphertext using OTP (XOR with key)
 */
public nonisolated func decrypt(key: [UInt8], ciphertext: [UInt8])throws  -> [UInt8] {
    return try  FfiConverterSequenceUInt8.lift(try rustCallWithError(FfiConverterTypeAshError.lift) {
    uniffi_ash_bindings_fn_func_decrypt(
        FfiConverterSequenceUInt8.lower(key),
        FfiConverterSequenceUInt8.lower(ciphertext),$0
    )
})
}
/**
 * Derive all tokens at once (conversation_id, auth_token, burn_token)
 */
public func deriveAllTokens(padBytes: [UInt8])throws  -> AuthTokens {
    return try  FfiConverterTypeAuthTokens.lift(try rustCallWithError(FfiConverterTypeAshError.lift) {
    uniffi_ash_bindings_fn_func_derive_all_tokens(
        FfiConverterSequenceUInt8.lower(padBytes),$0
    )
})
}
/**
 * Derive auth token from pad bytes (hex-encoded, 64 chars)
 * Used for API authentication (messages, polling, registration)
 */
public func deriveAuthToken(padBytes: [UInt8])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeAshError.lift) {
    uniffi_ash_bindings_fn_func_derive_auth_token(
        FfiConverterSequenceUInt8.lower(padBytes),$0
    )
})
}
/**
 * Derive burn token from pad bytes (hex-encoded, 64 chars)
 * Used specifically for burn operations (defense in depth)
 */
public func deriveBurnToken(padBytes: [UInt8])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeAshError.lift) {
    uniffi_ash_bindings_fn_func_derive_burn_token(
        FfiConverterSequenceUInt8.lower(padBytes),$0
    )
})
}
/**
 * Derive conversation ID from pad bytes (hex-encoded, 64 chars)
 */
public func deriveConversationId(padBytes: [UInt8])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeAshError.lift) {
    uniffi_ash_bindings_fn_func_derive_conversation_id(
        FfiConverterSequenceUInt8.lower(padBytes),$0
    )
})
}
/**
 * Encrypt plaintext using OTP (XOR with key)
 */
public nonisolated func encrypt(key: [UInt8], plaintext: [UInt8])throws  -> [UInt8] {
    return try  FfiConverterSequenceUInt8.lift(try rustCallWithError(FfiConverterTypeAshError.lift) {
    uniffi_ash_bindings_fn_func_encrypt(
        FfiConverterSequenceUInt8.lower(key),
        FfiConverterSequenceUInt8.lower(plaintext),$0
    )
})
}
/**
 * Generate 6-word mnemonic checksum from pad bytes
 */
public nonisolated func generateMnemonic(padBytes: [UInt8]) -> [String] {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_ash_bindings_fn_func_generate_mnemonic(
        FfiConverterSequenceUInt8.lower(padBytes),$0
    )
})
}
/**
 * Generate mnemonic with custom word count
 */
public nonisolated func generateMnemonicWithCount(padBytes: [UInt8], wordCount: UInt32) -> [String] {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_ash_bindings_fn_func_generate_mnemonic_with_count(
        FfiConverterSequenceUInt8.lower(padBytes),
        FfiConverterUInt32.lower(wordCount),$0
    )
})
}
/**
 * Get maximum passphrase length
 */
public func getMaxPassphraseLength() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_ash_bindings_fn_func_get_max_passphrase_length($0
    )
})
}
/**
 * Get minimum passphrase length
 */
public func getMinPassphraseLength() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_ash_bindings_fn_func_get_min_passphrase_length($0
    )
})
}
/**
 * Validate passphrase meets requirements (4-64 printable ASCII chars)
 */
public func validatePassphrase(passphrase: String) -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_ash_bindings_fn_func_validate_passphrase(
        FfiConverterString.lower(passphrase),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
nonisolated(unsafe) private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_ash_bindings_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_ash_bindings_checksum_func_create_fountain_generator() != 21416) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_func_decrypt() != 24750) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_func_derive_all_tokens() != 49844) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_func_derive_auth_token() != 14058) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_func_derive_burn_token() != 56541) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_func_derive_conversation_id() != 20229) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_func_encrypt() != 28557) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_func_generate_mnemonic() != 8039) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_func_generate_mnemonic_with_count() != 38577) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_func_get_max_passphrase_length() != 19825) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_func_get_min_passphrase_length() != 46202) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_func_validate_passphrase() != 11471) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_fountainframegenerator_block_size() != 4068) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_fountainframegenerator_generate_frame() != 37404) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_fountainframegenerator_next_frame() != 55964) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_fountainframegenerator_source_count() != 49617) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_fountainframegenerator_total_size() != 57404) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_fountainframereceiver_add_frame() != 42009) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_fountainframereceiver_blocks_received() != 21566) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_fountainframereceiver_get_result() != 17120) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_fountainframereceiver_is_complete() != 55359) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_fountainframereceiver_progress() != 18933) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_fountainframereceiver_source_count() != 43225) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_pad_as_bytes() != 57196) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_pad_available_for_sending() != 19640) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_pad_can_send() != 58381) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_pad_consume() != 64469) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_pad_consumed() != 16684) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_pad_consumed_back() != 8290) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_pad_consumed_front() != 32220) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_pad_is_exhausted() != 34846) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_pad_next_send_offset() != 20689) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_pad_remaining() != 32900) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_pad_total_size() != 20873) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_method_pad_update_peer_consumption() != 28070) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_constructor_fountainframereceiver_new() != 36123) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_constructor_pad_from_bytes() != 21075) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_constructor_pad_from_bytes_with_state() != 25438) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ash_bindings_checksum_constructor_pad_from_entropy() != 28891) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private nonisolated func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all