// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_CLONE_FRAME
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_CLONE_FRAME
void*_Nonnull uniffi_ash_bindings_fn_clone_frame(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_FREE_FRAME
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_FREE_FRAME
void uniffi_ash_bindings_fn_free_frame(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_CONSTRUCTOR_FRAME_DECODE
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_CONSTRUCTOR_FRAME_DECODE
void*_Nonnull uniffi_ash_bindings_fn_constructor_frame_decode(RustBuffer bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_CONSTRUCTOR_FRAME_NEW
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_CONSTRUCTOR_FRAME_NEW
void*_Nonnull uniffi_ash_bindings_fn_constructor_frame_new(uint16_t index, uint16_t total, RustBuffer payload, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_METHOD_FRAME_ENCODE
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_METHOD_FRAME_ENCODE
RustBuffer uniffi_ash_bindings_fn_method_frame_encode(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_METHOD_FRAME_GET_INDEX
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_METHOD_FRAME_GET_INDEX
uint16_t uniffi_ash_bindings_fn_method_frame_get_index(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_METHOD_FRAME_GET_PAYLOAD
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_METHOD_FRAME_GET_PAYLOAD
RustBuffer uniffi_ash_bindings_fn_method_frame_get_payload(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_METHOD_FRAME_GET_TOTAL
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_METHOD_FRAME_GET_TOTAL
uint16_t uniffi_ash_bindings_fn_method_frame_get_total(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_CLONE_PAD
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_CLONE_PAD
void*_Nonnull uniffi_ash_bindings_fn_clone_pad(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_FREE_PAD
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_FREE_PAD
void uniffi_ash_bindings_fn_free_pad(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_CONSTRUCTOR_PAD_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_CONSTRUCTOR_PAD_FROM_BYTES
void*_Nonnull uniffi_ash_bindings_fn_constructor_pad_from_bytes(RustBuffer bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_CONSTRUCTOR_PAD_FROM_ENTROPY
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_CONSTRUCTOR_PAD_FROM_ENTROPY
void*_Nonnull uniffi_ash_bindings_fn_constructor_pad_from_entropy(RustBuffer entropy, RustBuffer size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_METHOD_PAD_AS_BYTES
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_METHOD_PAD_AS_BYTES
RustBuffer uniffi_ash_bindings_fn_method_pad_as_bytes(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_METHOD_PAD_CONSUME
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_METHOD_PAD_CONSUME
RustBuffer uniffi_ash_bindings_fn_method_pad_consume(void*_Nonnull ptr, uint32_t n, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_METHOD_PAD_CONSUMED
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_METHOD_PAD_CONSUMED
uint64_t uniffi_ash_bindings_fn_method_pad_consumed(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_METHOD_PAD_IS_EXHAUSTED
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_METHOD_PAD_IS_EXHAUSTED
int8_t uniffi_ash_bindings_fn_method_pad_is_exhausted(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_METHOD_PAD_REMAINING
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_METHOD_PAD_REMAINING
uint64_t uniffi_ash_bindings_fn_method_pad_remaining(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_METHOD_PAD_TOTAL_SIZE
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_METHOD_PAD_TOTAL_SIZE
uint64_t uniffi_ash_bindings_fn_method_pad_total_size(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_FUNC_CREATE_FRAMES
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_FUNC_CREATE_FRAMES
RustBuffer uniffi_ash_bindings_fn_func_create_frames(RustBuffer pad_bytes, uint32_t max_payload, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_FUNC_DECRYPT
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_FUNC_DECRYPT
RustBuffer uniffi_ash_bindings_fn_func_decrypt(RustBuffer key, RustBuffer ciphertext, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_FUNC_ENCRYPT
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_FUNC_ENCRYPT
RustBuffer uniffi_ash_bindings_fn_func_encrypt(RustBuffer key, RustBuffer plaintext, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_FUNC_GENERATE_MNEMONIC
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_FUNC_GENERATE_MNEMONIC
RustBuffer uniffi_ash_bindings_fn_func_generate_mnemonic(RustBuffer pad_bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_FUNC_GENERATE_MNEMONIC_WITH_COUNT
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_FUNC_GENERATE_MNEMONIC_WITH_COUNT
RustBuffer uniffi_ash_bindings_fn_func_generate_mnemonic_with_count(RustBuffer pad_bytes, uint32_t word_count, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_FUNC_RECONSTRUCT_PAD
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_FN_FUNC_RECONSTRUCT_PAD
RustBuffer uniffi_ash_bindings_fn_func_reconstruct_pad(RustBuffer frames, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUSTBUFFER_ALLOC
RustBuffer ffi_ash_bindings_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_ash_bindings_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUSTBUFFER_FREE
void ffi_ash_bindings_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUSTBUFFER_RESERVE
RustBuffer ffi_ash_bindings_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_U8
void ffi_ash_bindings_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_U8
void ffi_ash_bindings_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_U8
void ffi_ash_bindings_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_ash_bindings_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_I8
void ffi_ash_bindings_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_I8
void ffi_ash_bindings_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_I8
void ffi_ash_bindings_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_I8
int8_t ffi_ash_bindings_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_U16
void ffi_ash_bindings_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_U16
void ffi_ash_bindings_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_U16
void ffi_ash_bindings_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_ash_bindings_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_I16
void ffi_ash_bindings_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_I16
void ffi_ash_bindings_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_I16
void ffi_ash_bindings_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_I16
int16_t ffi_ash_bindings_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_U32
void ffi_ash_bindings_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_U32
void ffi_ash_bindings_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_U32
void ffi_ash_bindings_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_ash_bindings_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_I32
void ffi_ash_bindings_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_I32
void ffi_ash_bindings_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_I32
void ffi_ash_bindings_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_I32
int32_t ffi_ash_bindings_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_U64
void ffi_ash_bindings_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_U64
void ffi_ash_bindings_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_U64
void ffi_ash_bindings_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_ash_bindings_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_I64
void ffi_ash_bindings_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_I64
void ffi_ash_bindings_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_I64
void ffi_ash_bindings_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_I64
int64_t ffi_ash_bindings_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_F32
void ffi_ash_bindings_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_F32
void ffi_ash_bindings_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_F32
void ffi_ash_bindings_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_F32
float ffi_ash_bindings_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_F64
void ffi_ash_bindings_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_F64
void ffi_ash_bindings_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_F64
void ffi_ash_bindings_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_F64
double ffi_ash_bindings_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_POINTER
void ffi_ash_bindings_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_POINTER
void ffi_ash_bindings_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_POINTER
void ffi_ash_bindings_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_ash_bindings_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_ash_bindings_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_ash_bindings_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_ash_bindings_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_ash_bindings_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_POLL_VOID
void ffi_ash_bindings_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_CANCEL_VOID
void ffi_ash_bindings_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_FREE_VOID
void ffi_ash_bindings_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_RUST_FUTURE_COMPLETE_VOID
void ffi_ash_bindings_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_FUNC_CREATE_FRAMES
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_FUNC_CREATE_FRAMES
uint16_t uniffi_ash_bindings_checksum_func_create_frames(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_FUNC_DECRYPT
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_FUNC_DECRYPT
uint16_t uniffi_ash_bindings_checksum_func_decrypt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_FUNC_ENCRYPT
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_FUNC_ENCRYPT
uint16_t uniffi_ash_bindings_checksum_func_encrypt(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_FUNC_GENERATE_MNEMONIC
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_FUNC_GENERATE_MNEMONIC
uint16_t uniffi_ash_bindings_checksum_func_generate_mnemonic(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_FUNC_GENERATE_MNEMONIC_WITH_COUNT
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_FUNC_GENERATE_MNEMONIC_WITH_COUNT
uint16_t uniffi_ash_bindings_checksum_func_generate_mnemonic_with_count(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_FUNC_RECONSTRUCT_PAD
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_FUNC_RECONSTRUCT_PAD
uint16_t uniffi_ash_bindings_checksum_func_reconstruct_pad(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_METHOD_FRAME_ENCODE
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_METHOD_FRAME_ENCODE
uint16_t uniffi_ash_bindings_checksum_method_frame_encode(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_METHOD_FRAME_GET_INDEX
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_METHOD_FRAME_GET_INDEX
uint16_t uniffi_ash_bindings_checksum_method_frame_get_index(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_METHOD_FRAME_GET_PAYLOAD
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_METHOD_FRAME_GET_PAYLOAD
uint16_t uniffi_ash_bindings_checksum_method_frame_get_payload(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_METHOD_FRAME_GET_TOTAL
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_METHOD_FRAME_GET_TOTAL
uint16_t uniffi_ash_bindings_checksum_method_frame_get_total(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_METHOD_PAD_AS_BYTES
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_METHOD_PAD_AS_BYTES
uint16_t uniffi_ash_bindings_checksum_method_pad_as_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_METHOD_PAD_CONSUME
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_METHOD_PAD_CONSUME
uint16_t uniffi_ash_bindings_checksum_method_pad_consume(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_METHOD_PAD_CONSUMED
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_METHOD_PAD_CONSUMED
uint16_t uniffi_ash_bindings_checksum_method_pad_consumed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_METHOD_PAD_IS_EXHAUSTED
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_METHOD_PAD_IS_EXHAUSTED
uint16_t uniffi_ash_bindings_checksum_method_pad_is_exhausted(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_METHOD_PAD_REMAINING
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_METHOD_PAD_REMAINING
uint16_t uniffi_ash_bindings_checksum_method_pad_remaining(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_METHOD_PAD_TOTAL_SIZE
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_METHOD_PAD_TOTAL_SIZE
uint16_t uniffi_ash_bindings_checksum_method_pad_total_size(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_CONSTRUCTOR_FRAME_DECODE
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_CONSTRUCTOR_FRAME_DECODE
uint16_t uniffi_ash_bindings_checksum_constructor_frame_decode(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_CONSTRUCTOR_FRAME_NEW
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_CONSTRUCTOR_FRAME_NEW
uint16_t uniffi_ash_bindings_checksum_constructor_frame_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_CONSTRUCTOR_PAD_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_CONSTRUCTOR_PAD_FROM_BYTES
uint16_t uniffi_ash_bindings_checksum_constructor_pad_from_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_CONSTRUCTOR_PAD_FROM_ENTROPY
#define UNIFFI_FFIDEF_UNIFFI_ASH_BINDINGS_CHECKSUM_CONSTRUCTOR_PAD_FROM_ENTROPY
uint16_t uniffi_ash_bindings_checksum_constructor_pad_from_entropy(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_ASH_BINDINGS_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_ASH_BINDINGS_UNIFFI_CONTRACT_VERSION
uint32_t ffi_ash_bindings_uniffi_contract_version(void
    
);
#endif

